// c64/frontend/src/App.svelte
<script>
  import { onMount, onDestroy } from 'svelte'
  import Chart from 'chart.js/auto'

  const API_BASE = 'http://localhost:8080/api'

  let devices = []
  let selectedDevice = ''
  let sensorData = []
  let stats = { count_last_hour: 0 }
  let chart = null
  let canvas = null
  let loading = false
  let error = ''
  let activeTab = 'dashboard'

  let rules = []
  let editingRule = null
  let newRule = {
    name: '',
    description: '',
    condition: 'value > 70 && device_id in [1..10]',
    action: {
      type: 'actuator',
      actuator: 'fan_01'
    },
    enabled: true
  }

  const sensorColors = {
    temperature: 'rgb(255, 99, 132)',
    humidity: 'rgb(54, 162, 235)',
    pressure: 'rgb(75, 192, 192)'
  }

  const sensorLabels = {
    temperature: '温度 (°C)',
    humidity: '湿度 (%)',
    pressure: '气压 (hPa)'
  }

  const ruleTemplates = [
    { name: '高温告警', condition: 'value > 70', actuator: 'fan_01', desc: '温度超过70度启动风扇' },
    { name: '高湿告警', condition: 'value > 85', actuator: 'dehumidifier_01', desc: '湿度超过85%启动除湿机' },
    { name: '设备范围告警', condition: 'value > 60 && device_id in [1..20]', actuator: 'alarm_01', desc: '1-20号设备温度告警' }
  ]

  async function fetchDevices() {
    try {
      const res = await fetch(`${API_BASE}/devices`)
      devices = await res.json()
      if (devices.length > 0 && !selectedDevice) {
        selectedDevice = devices[0]
      }
    } catch (e) {
      error = '获取设备列表失败'
    }
  }

  async function fetchSensorData() {
    if (!selectedDevice) return
    loading = true
    try {
      const res = await fetch(`${API_BASE}/sensors?device_id=${selectedDevice}&limit=50`)
      sensorData = await res.json()
      updateChart()
    } catch (e) {
      error = '获取传感器数据失败'
    }
    loading = false
  }

  async function fetchStats() {
    try {
      const res = await fetch(`${API_BASE}/stats`)
      stats = await res.json()
    } catch (e) {}
  }

  async function fetchRules() {
    try {
      const res = await fetch(`${API_BASE}/rules`)
      rules = await res.json()
    } catch (e) {
      console.error('获取规则失败:', e)
    }
  }

  async function saveRule() {
    try {
      const ruleToSave = editingRule || newRule
      const url = editingRule 
        ? `${API_BASE}/rules/${editingRule.id}` 
        : `${API_BASE}/rules`
      const method = editingRule ? 'PUT' : 'POST'

      const res = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(ruleToSave)
      })

      if (res.ok) {
        await fetchRules()
        resetRuleForm()
      }
    } catch (e) {
      error = '保存规则失败'
    }
  }

  async function deleteRule(id) {
    if (!confirm('确定要删除这条规则吗？')) return
    try {
      await fetch(`${API_BASE}/rules/${id}`, { method: 'DELETE' })
      await fetchRules()
    } catch (e) {
      error = '删除规则失败'
    }
  }

  function editRule(rule) {
    editingRule = { ...rule }
  }

  function resetRuleForm() {
    editingRule = null
    newRule = {
      name: '',
      description: '',
      condition: 'value > 70 && device_id in [1..10]',
      action: {
        type: 'actuator',
        actuator: 'fan_01'
      },
      enabled: true
    }
  }

  function applyTemplate(template) {
    if (editingRule) {
      editingRule.condition = template.condition
      editingRule.action.actuator = template.actuator
      if (!editingRule.name) editingRule.name = template.name
      if (!editingRule.description) editingRule.description = template.desc
    } else {
      newRule.condition = template.condition
      newRule.action.actuator = template.actuator
      newRule.name = template.name
      newRule.description = template.desc
    }
  }

  function updateChart() {
    if (!canvas) return

    const bySensor = {}
    sensorData.forEach(d => {
      if (!bySensor[d.sensor_type]) {
        bySensor[d.sensor_type] = []
      }
      bySensor[d.sensor_type].push({
        x: new Date(d.timestamp),
        y: d.value
      })
    })

    Object.keys(bySensor).forEach(key => {
      bySensor[key].sort((a, b) => a.x - b.x)
    })

    const datasets = Object.keys(bySensor).map(sensor => ({
      label: sensorLabels[sensor] || sensor,
      data: bySensor[sensor],
      borderColor: sensorColors[sensor] || 'gray',
      backgroundColor: (sensorColors[sensor] || 'gray').replace('rgb', 'rgba').replace(')', ', 0.1)'),
      tension: 0.4,
      fill: true
    }))

    if (chart) {
      chart.data.datasets = datasets
      chart.update('none')
    } else {
      chart = new Chart(canvas, {
        type: 'line',
        data: { datasets },
        options: {
          responsive: true,
          maintainAspectRatio: false,
          interaction: {
            mode: 'index',
            intersect: false,
          },
          scales: {
            x: {
              type: 'time',
              display: true,
              title: {
                display: true,
                text: '时间'
              },
              ticks: {
                maxTicksLimit: 10
              }
            },
            y: {
              display: true,
              title: {
                display: true,
                text: '数值'
              }
            }
          },
          plugins: {
            legend: {
              position: 'top',
            }
          }
        }
      })
    }
  }

  $: if (selectedDevice) {
    fetchSensorData()
  }

  let intervalId

  onMount(() => {
    fetchDevices()
    fetchStats()
    fetchSensorData()
    fetchRules()
    
    intervalId = setInterval(() => {
      fetchSensorData()
      fetchStats()
    }, 2000)
  })

  onDestroy(() => {
    if (intervalId) clearInterval(intervalId)
    if (chart) chart.destroy()
  })
</script>

<main>
  <header>
    <h1>🌐 IoT 实时监控面板</h1>
    <div class="stats">
      <div class="stat-card">
        <span class="stat-value">{stats.count_last_hour}</span>
        <span class="stat-label">近1小时数据点</span>
      </div>
      <div class="stat-card">
        <span class="stat-value">{devices.length}</span>
        <span class="stat-label">在线设备数</span>
      </div>
      <div class="stat-card">
        <span class="stat-value">{rules.length}</span>
        <span class="stat-label">边缘规则数</span>
      </div>
    </div>
  </header>

  <div class="tabs">
    <button 
      class="tab {activeTab === 'dashboard' ? 'active' : ''}"
      on:click={() => activeTab = 'dashboard'}
    >
      📊 监控面板
    </button>
    <button 
      class="tab {activeTab === 'rules' ? 'active' : ''}"
      on:click={() => activeTab = 'rules'}
    >
      ⚙️ 边缘规则
    </button>
  </div>

  {#if activeTab === 'dashboard'}
    <div class="controls">
      <select bind:value={selectedDevice} disabled={devices.length === 0}>
        <option value="">选择设备</option>
        {#each devices as device}
          <option value={device}>{device}</option>
        {/each}
      </select>
      <button on:click={fetchSensorData} disabled={loading}>
        {loading ? '刷新中...' : '🔄 刷新'}
      </button>
    </div>

    {#if error}
      <div class="error">{error}</div>
    {/if}

    <div class="chart-container">
      <canvas bind:this={canvas}></canvas>
    </div>

    <div class="sensor-stats">
      {#each ['temperature', 'humidity', 'pressure'] as sensor}
        {@const data = sensorData.filter(d => d.sensor_type === sensor)}
        {@const latest = data[0]}
        <div class="sensor-card" style="--color: {sensorColors[sensor]}">
          <div class="sensor-icon">
            {#if sensor === 'temperature'}🌡️
            {:else if sensor === 'humidity'}💧
            {:else}⚡{/if}
          </div>
          <div class="sensor-info">
            <h3>{sensorLabels[sensor]}</h3>
            <p class="sensor-value">
              {latest ? latest.value.toFixed(2) : '--'}
              {#if sensor === 'temperature'}°C
              {:else if sensor === 'humidity'}%
              {:else}hPa
              {/if}
            </p>
          </div>
        </div>
      {/each}
    </div>

    {#if sensorData.length > 0}
      <div class="data-table">
        <h3>📊 最近数据</h3>
        <table>
          <thead>
            <tr>
              <th>时间</th>
              <th>传感器</th>
              <th>数值</th>
            </tr>
          </thead>
          <tbody>
            {#each sensorData.slice(0, 10) as d}
              <tr>
                <td>{new Date(d.timestamp).toLocaleTimeString('zh-CN')}</td>
                <td>{sensorLabels[d.sensor_type] || d.sensor_type}</td>
                <td>{d.value.toFixed(2)}</td>
              </tr>
            {/each}
          </tbody>
        </table>
      </div>
    {/if}
  {/if}

  {#if activeTab === 'rules'}
    <div class="rules-container">
      <div class="rule-form">
        <h3>{editingRule ? '📝 编辑规则' : '➕ 新建规则'}</h3>
        
        <div class="form-group">
          <label>规则名称</label>
          <input 
            bind:value={editingRule ? editingRule.name : newRule.name}
            placeholder="例如：高温告警"
          />
        </div>

        <div class="form-group">
          <label>描述</label>
          <input 
            bind:value={editingRule ? editingRule.description : newRule.description}
            placeholder="规则用途说明"
          />
        </div>

        <div class="form-group">
          <label>条件表达式</label>
          <textarea 
            bind:value={editingRule ? editingRule.condition : newRule.condition}
            rows="2"
            placeholder="例如：value > 70 && device_id in [1..10]"
          />
          <div class="templates">
            <span class="template-label">快速模板:</span>
            {#each ruleTemplates as template}
              <button 
                class="template-btn"
                on:click={() => applyTemplate(template)}
              >
                {template.name}
              </button>
            {/each}
          </div>
        </div>

        <div class="form-row">
          <div class="form-group">
            <label>动作类型</label>
            <select bind:value={editingRule ? editingRule.action.type : newRule.action.type}>
              <option value="actuator">切换执行器</option>
              <option value="on">开启执行器</option>
              <option value="off">关闭执行器</option>
            </select>
          </div>

          <div class="form-group">
            <label>执行器名称</label>
            <input 
              bind:value={editingRule ? editingRule.action.actuator : newRule.action.actuator}
              placeholder="例如：fan_01"
            />
          </div>
        </div>

        <div class="form-group checkbox">
          <label>
            <input 
              type="checkbox" 
              bind:checked={editingRule ? editingRule.enabled : newRule.enabled}
            />
            启用规则
          </label>
        </div>

        <div class="form-actions">
          {#if editingRule}
            <button class="btn-secondary" on:click={resetRuleForm}>取消编辑</button>
          {/if}
          <button class="btn-primary" on:click={saveRule}>
            {editingRule ? '更新规则' : '创建规则'}
          </button>
        </div>
      </div>

      <div class="rules-list">
        <h3>📋 已有规则 ({rules.length})</h3>
        {#if rules.length === 0}
          <p class="empty-state">暂无规则，创建第一条规则开始使用边缘计算</p>
        {:else}
          {#each rules as rule}
            <div class="rule-card {!rule.enabled ? 'disabled' : ''}">
              <div class="rule-header">
                <span class="rule-name">{rule.name}</span>
                <span class="rule-status {rule.enabled ? 'enabled' : 'disabled'}">
                  {rule.enabled ? '✅ 已启用' : '❌ 已禁用'}
                </span>
              </div>
              {#if rule.description}
                <p class="rule-desc">{rule.description}</p>
              {/if}
              <div class="rule-detail">
                <code>IF {rule.condition}</code>
                <br />
                <code>THEN {rule.action.type} {rule.action.actuator}</code>
              </div>
              <div class="rule-actions">
                <button class="btn-small" on:click={() => editRule(rule)}>编辑</button>
                <button class="btn-small btn-danger" on:click={() => deleteRule(rule.id)}>删除</button>
              </div>
            </div>
          {/each}
        {/if}
      </div>
    </div>
  {/if}
</main>

<style>
  main {
    max-width: 1200px;
    margin: 0 auto;
    padding: 20px;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
  }

  header {
    text-align: center;
    margin-bottom: 30px;
  }

  h1 {
    color: #1e293b;
    font-size: 2rem;
    margin-bottom: 20px;
  }

  h3 {
    margin-top: 0;
    color: #1e293b;
  }

  .stats {
    display: flex;
    justify-content: center;
    gap: 20px;
    flex-wrap: wrap;
  }

  .stat-card {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
    padding: 20px 40px;
    border-radius: 12px;
    display: flex;
    flex-direction: column;
    align-items: center;
    box-shadow: 0 4px 15px rgba(102, 126, 234, 0.4);
  }

  .stat-value {
    font-size: 2rem;
    font-weight: bold;
  }

  .stat-label {
    font-size: 0.9rem;
    opacity: 0.9;
  }

  .tabs {
    display: flex;
    gap: 10px;
    margin-bottom: 20px;
    border-bottom: 2px solid #e2e8f0;
    padding-bottom: 10px;
  }

  .tab {
    padding: 10px 20px;
    border: none;
    background: none;
    font-size: 1rem;
    cursor: pointer;
    border-radius: 8px 8px 0 0;
    transition: all 0.2s;
  }

  .tab.active {
    background: #3b82f6;
    color: white;
  }

  .tab:hover:not(.active) {
    background: #f1f5f9;
  }

  .controls {
    display: flex;
    gap: 15px;
    margin-bottom: 20px;
    align-items: center;
    flex-wrap: wrap;
  }

  select, button, input, textarea {
    padding: 12px 20px;
    border: 2px solid #e2e8f0;
    border-radius: 8px;
    font-size: 1rem;
    cursor: pointer;
    font-family: inherit;
  }

  input, textarea {
    cursor: text;
  }

  textarea {
    resize: vertical;
    min-height: 60px;
  }

  button {
    background: #3b82f6;
    color: white;
    border: none;
    transition: background 0.2s;
  }

  button:hover:not(:disabled) {
    background: #2563eb;
  }

  button:disabled {
    background: #94a3b8;
    cursor: not-allowed;
  }

  .btn-primary {
    background: #10b981;
  }

  .btn-primary:hover {
    background: #059669;
  }

  .btn-secondary {
    background: #64748b;
  }

  .btn-secondary:hover {
    background: #475569;
  }

  .btn-small {
    padding: 6px 12px;
    font-size: 0.875rem;
  }

  .btn-danger {
    background: #ef4444;
  }

  .btn-danger:hover {
    background: #dc2626;
  }

  .error {
    background: #fee2e2;
    color: #dc2626;
    padding: 12px;
    border-radius: 8px;
    margin-bottom: 20px;
  }

  .chart-container {
    background: white;
    border-radius: 12px;
    padding: 20px;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    margin-bottom: 20px;
    height: 400px;
  }

  .sensor-stats {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
    gap: 20px;
    margin-bottom: 30px;
  }

  .sensor-card {
    background: white;
    border-radius: 12px;
    padding: 20px;
    display: flex;
    align-items: center;
    gap: 15px;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    border-left: 4px solid var(--color);
  }

  .sensor-icon {
    font-size: 2.5rem;
  }

  .sensor-info h3 {
    margin: 0;
    color: #64748b;
    font-size: 0.9rem;
  }

  .sensor-value {
    margin: 5px 0 0;
    font-size: 1.8rem;
    font-weight: bold;
    color: #1e293b;
  }

  .data-table {
    background: white;
    border-radius: 12px;
    padding: 20px;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
  }

  table {
    width: 100%;
    border-collapse: collapse;
  }

  th, td {
    padding: 12px;
    text-align: left;
    border-bottom: 1px solid #e2e8f0;
  }

  th {
    background: #f8fafc;
    font-weight: 600;
    color: #475569;
  }

  tr:hover {
    background: #f8fafc;
  }

  .rules-container {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 20px;
  }

  @media (max-width: 768px) {
    .rules-container {
      grid-template-columns: 1fr;
    }
  }

  .rule-form, .rules-list {
    background: white;
    border-radius: 12px;
    padding: 20px;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
  }

  .form-group {
    margin-bottom: 15px;
  }

  .form-group label {
    display: block;
    margin-bottom: 5px;
    font-weight: 500;
    color: #475569;
  }

  .form-group input,
  .form-group select,
  .form-group textarea {
    width: 100%;
    box-sizing: border-box;
  }

  .form-group.checkbox label {
    display: flex;
    align-items: center;
    gap: 8px;
    cursor: pointer;
  }

  .form-row {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 15px;
  }

  .templates {
    margin-top: 8px;
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
    align-items: center;
  }

  .template-label {
    font-size: 0.875rem;
    color: #64748b;
  }

  .template-btn {
    padding: 4px 10px;
    font-size: 0.8rem;
    background: #e0f2fe;
    color: #0284c7;
    border: none;
    border-radius: 4px;
  }

  .template-btn:hover {
    background: #bae6fd;
  }

  .form-actions {
    display: flex;
    gap: 10px;
    justify-content: flex-end;
    margin-top: 20px;
  }

  .rule-card {
    background: #f8fafc;
    border-radius: 8px;
    padding: 15px;
    margin-bottom: 10px;
    border-left: 4px solid #3b82f6;
  }

  .rule-card.disabled {
    opacity: 0.6;
    border-left-color: #94a3b8;
  }

  .rule-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 8px;
  }

  .rule-name {
    font-weight: 600;
    color: #1e293b;
  }

  .rule-status {
    font-size: 0.875rem;
  }

  .rule-status.enabled {
    color: #059669;
  }

  .rule-status.disabled {
    color: #64748b;
  }

  .rule-desc {
    margin: 0 0 10px 0;
    color: #64748b;
    font-size: 0.9rem;
  }

  .rule-detail {
    background: white;
    padding: 10px;
    border-radius: 6px;
    font-family: 'Fira Code', monospace;
    font-size: 0.875rem;
    color: #1e293b;
    margin-bottom: 10px;
  }

  .rule-detail code {
    display: block;
  }

  .rule-actions {
    display: flex;
    gap: 8px;
    justify-content: flex-end;
  }

  .empty-state {
    text-align: center;
    color: #64748b;
    padding: 40px;
  }
</style>

// c40/frontend/src/App.vue
<template>
  <div class="app">
    <header class="header">
      <h1>🏭 工业设备监控系统</h1>
      <div class="header-right">
        <div class="alert-banner" v-if="activeAlerts.length > 0">
          <span class="blink">⚠️ 告警中: {{ activeAlerts.length }} 个</span>
        </div>
        <div class="alert-banner anomaly" v-if="anomalies.length > 0">
          <span class="blink">🚨 异常模式: {{ anomalies.length }} 个</span>
        </div>
      </div>
    </header>

    <div class="main-content">
      <aside class="sidebar">
        <div class="tabs">
          <button class="tab-btn" :class="{active: currentTab === 'devices'}" @click="currentTab = 'devices'">
            设备列表
          </button>
          <button class="tab-btn" :class="{active: currentTab === 'rules'}" @click="currentTab = 'rules'">
            规则管理
          </button>
        </div>

        <div v-if="currentTab === 'devices'" class="device-list">
          <div 
            v-for="device in devices" 
            :key="device.deviceId"
            class="device-item"
            :class="{ 'has-alert': device.hasAlert, 'selected': selectedDevice === device.deviceId }"
            @click="selectDevice(device.deviceId)"
          >
            <span class="device-id">{{ device.deviceId }}</span>
            <span class="device-temp" :class="getTemperatureClass(device.lastTemperature)">
              {{ device.lastTemperature.toFixed(1) }}°C
            </span>
            <span v-if="device.hasAlert" class="alert-indicator blink">🔴</span>
          </div>
        </div>

        <div v-if="currentTab === 'rules'" class="rules-panel">
          <div class="rule-form">
            <h3>新建/编辑规则</h3>
            <input v-model="editingRule.name" placeholder="规则名称" class="form-input" />
            <textarea v-model="editingRule.description" placeholder="规则描述" class="form-textarea" rows="2" />
            
            <div class="form-row">
              <label>窗口大小(秒):</label>
              <input v-model.number="editingRule.windowSeconds" type="number" class="form-input small" />
            </div>
            
            <div class="form-row">
              <label>严重级别:</label>
              <select v-model="editingRule.severity" class="form-select">
                <option value="LOW">低</option>
                <option value="MEDIUM">中</option>
                <option value="HIGH">高</option>
                <option value="CRITICAL">严重</option>
              </select>
            </div>

            <div class="conditions-section">
              <h4>条件配置</h4>
              <div v-for="(cond, idx) in editingRule.conditions" :key="idx" class="condition-item">
                <div class="condition-row">
                  <select v-model="cond.metric" class="form-select small">
                    <option value="temperature">温度</option>
                    <option value="vibration">振动</option>
                    <option value="current">电流</option>
                  </select>
                  <select v-model="cond.aggregation" class="form-select small">
                    <option value="last">当前值</option>
                    <option value="avg">平均值</option>
                    <option value="max">最大值</option>
                    <option value="min">最小值</option>
                    <option value="change">变化量</option>
                    <option value="changePercent">变化率%</option>
                  </select>
                  <select v-model="cond.operator" class="form-select small">
                    <option value=">">></option>
                    <option value=">=">>=</option>
                    <option value="<"><</option>
                    <option value="<="><=</option>
                    <option value="==">=</option>
                  </select>
                  <input v-model.number="cond.value" type="number" step="0.1" class="form-input small" />
                  <button @click="removeCondition(idx)" class="btn-small danger">✕</button>
                </div>
              </div>
              <button @click="addCondition" class="btn btn-secondary">+ 添加条件</button>
            </div>

            <input v-model="editingRule.notificationMessage" placeholder="告警消息" class="form-input" />
            
            <div class="form-actions">
              <button @click="saveRule" class="btn btn-primary">保存</button>
              <button @click="resetRule" class="btn btn-secondary">重置</button>
            </div>
          </div>

          <div class="rules-list">
            <h4>已有规则</h4>
            <div v-for="rule in rules" :key="rule.id" class="rule-item">
              <div class="rule-header">
                <span class="rule-name">{{ rule.name }}</span>
                <span class="rule-severity" :class="rule.severity.toLowerCase()">{{ rule.severity }}</span>
              </div>
              <p class="rule-desc">{{ rule.description }}</p>
              <div class="rule-actions">
                <button @click="editRule(rule)" class="btn-small">编辑</button>
                <button @click="deleteRule(rule.id)" class="btn-small danger">删除</button>
                <button @click="toggleRule(rule)" class="btn-small" :class="{active: rule.enabled}">
                  {{ rule.enabled ? '启用' : '禁用' }}
                </button>
              </div>
            </div>
          </div>
        </div>
      </aside>

      <section class="content">
        <div v-if="selectedDevice" class="device-detail">
          <h2>设备详情: {{ selectedDevice }}</h2>
          
          <div class="chart-container">
            <h3>实时温度曲线</h3>
            <Line :data="chartData" :options="chartOptions" />
          </div>

          <div class="chart-container">
            <h3>预测温度曲线 (未来1小时)</h3>
            <Line :data="predictionChartData" :options="predictionChartOptions" />
          </div>

          <div v-if="deviceAnomalies.length > 0" class="anomalies-section">
            <h3>检测到的异常</h3>
            <div v-for="anomaly in deviceAnomalies" :key="anomaly.id" class="anomaly-item">
              <div class="anomaly-header">
                <span class="anomaly-rule">{{ anomaly.ruleName }}</span>
                <span class="anomaly-severity" :class="anomaly.severity.toLowerCase()">{{ anomaly.severity }}</span>
                <span class="anomaly-time">{{ formatTime(anomaly.detectedAt) }}</span>
              </div>
              <p class="anomaly-msg">{{ anomaly.message }}</p>
              <button @click="acknowledgeAnomaly(anomaly.id)" class="btn-small">确认</button>
            </div>
          </div>
        </div>

        <div v-else class="no-selection">
          <p>请从左侧选择一个设备查看详情</p>
        </div>
      </section>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, onUnmounted, computed } from 'vue'
import { Line } from 'vue-chartjs'
import { Chart as ChartJS, CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend } from 'chart.js'
import SockJS from 'sockjs-client'
import { Client } from '@stomp/stompjs'
import axios from 'axios'

ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend)

const devices = ref([])
const activeAlerts = ref([])
const anomalies = ref([])
const deviceAnomalies = ref([])
const selectedDevice = ref(null)
const historicalData = ref([])
const predictionData = ref([])
const stompClient = ref(null)
const currentTab = ref('devices')
const rules = ref([])

const editingRule = ref({
  name: '',
  description: '',
  enabled: true,
  windowSeconds: 30,
  severity: 'MEDIUM',
  conditions: [],
  notificationMessage: ''
})

const chartData = computed(() => ({
  labels: historicalData.value.map(d => {
    const date = new Date(d.timestamp)
    return date.toLocaleTimeString()
  }),
  datasets: [{
    label: '实际温度',
    data: historicalData.value.map(d => d.temperature),
    borderColor: '#4bc0c0',
    backgroundColor: 'rgba(75, 192, 192, 0.1)',
    tension: 0.4,
    fill: true
  }]
}))

const predictionChartData = computed(() => ({
  labels: predictionData.value.map(d => {
    const date = new Date(d.timestamp)
    return date.toLocaleTimeString()
  }),
  datasets: [{
    label: '预测温度',
    data: predictionData.value.map(d => d.temperature),
    borderColor: '#ff6b6b',
    backgroundColor: 'rgba(255, 107, 107, 0.1)',
    borderDash: [5, 5],
    tension: 0.4,
    fill: true
  }]
}))

const chartOptions = {
  responsive: true,
  maintainAspectRatio: false,
  plugins: { legend: { labels: { color: '#eee' } } },
  scales: {
    x: { ticks: { color: '#aaa' }, grid: { color: 'rgba(255,255,255,0.1)' } },
    y: { ticks: { color: '#aaa' }, grid: { color: 'rgba(255,255,255,0.1)' } }
  }
}

const predictionChartOptions = {
  ...chartOptions
}

const getTemperatureClass = (temp) => {
  if (temp > 75) return 'temp-critical'
  if (temp > 60) return 'temp-warning'
  return 'temp-normal'
}

const formatTime = (timeStr) => {
  return new Date(timeStr).toLocaleString()
}

const selectDevice = async (deviceId) => {
  selectedDevice.value = deviceId
  await loadDeviceData(deviceId)
  await loadDeviceAnomalies(deviceId)
}

const loadDeviceData = async (deviceId) => {
  try {
    const [historyRes, predictionRes] = await Promise.all([
      axios.get(`/api/devices/${deviceId}/history`),
      axios.get(`/api/devices/${deviceId}/predictions`)
    ])
    historicalData.value = historyRes.data
    predictionData.value = predictionRes.data
  } catch (error) {
    console.error('加载设备数据失败:', error)
  }
}

const loadDeviceAnomalies = async (deviceId) => {
  try {
    const res = await axios.get(`/api/rules/anomalies/${deviceId}`)
    deviceAnomalies.value = res.data
  } catch (error) {
    console.error('加载设备异常失败:', error)
  }
}

const acknowledgeAnomaly = async (eventId) => {
  try {
    await axios.post(`/api/rules/anomalies/${eventId}/acknowledge`)
    loadAnomalies()
    if (selectedDevice.value) {
      loadDeviceAnomalies(selectedDevice.value)
    }
  } catch (error) {
    console.error('确认异常失败:', error)
  }
}

const loadDevices = async () => {
  try {
    const res = await axios.get('/api/devices')
    devices.value = res.data
  } catch (error) {
    console.error('加载设备列表失败:', error)
  }
}

const loadAlerts = async () => {
  try {
    const res = await axios.get('/api/alerts')
    activeAlerts.value = res.data
  } catch (error) {
    console.error('加载告警失败:', error)
  }
}

const loadAnomalies = async () => {
  try {
    const res = await axios.get('/api/rules/anomalies')
    anomalies.value = res.data
  } catch (error) {
    console.error('加载异常失败:', error)
  }
}

const loadRules = async () => {
  try {
    const res = await axios.get('/api/rules')
    rules.value = res.data
  } catch (error) {
    console.error('加载规则失败:', error)
  }
}

const addCondition = () => {
  editingRule.value.conditions.push({
    metric: 'temperature',
    operator: '>',
    value: 0,
    aggregation: 'last'
  })
}

const removeCondition = (idx) => {
  editingRule.value.conditions.splice(idx, 1)
}

const editRule = (rule) => {
  editingRule.value = JSON.parse(JSON.stringify(rule))
}

const resetRule = () => {
  editingRule.value = {
    name: '',
    description: '',
    enabled: true,
    windowSeconds: 30,
    severity: 'MEDIUM',
    conditions: [],
    notificationMessage: ''
  }
}

const saveRule = async () => {
  try {
    if (editingRule.value.id) {
      await axios.put(`/api/rules/${editingRule.value.id}`, editingRule.value)
    } else {
      await axios.post('/api/rules', editingRule.value)
    }
    await loadRules()
    resetRule()
  } catch (error) {
    console.error('保存规则失败:', error)
  }
}

const deleteRule = async (ruleId) => {
  if (!confirm('确定删除此规则?')) return
  try {
    await axios.delete(`/api/rules/${ruleId}`)
    await loadRules()
  } catch (error) {
    console.error('删除规则失败:', error)
  }
}

const toggleRule = async (rule) => {
  rule.enabled = !rule.enabled
  try {
    await axios.put(`/api/rules/${rule.id}`, rule)
    await loadRules()
  } catch (error) {
    console.error('更新规则失败:', error)
  }
}

const connectWebSocket = () => {
  stompClient.value = new Client({
    webSocketFactory: () => new SockJS('http://localhost:8080/ws'),
    reconnectDelay: 3000,
    heartbeatIncoming: 4000,
    heartbeatOutgoing: 4000,
    onConnect: () => {
      console.log('WebSocket 已连接，订阅告警主题...')
      stompClient.value.subscribe('/topic/alerts', (message) => {
        try {
          const alert = JSON.parse(message.body)
          console.log('收到告警:', alert)
          loadAlerts()
          loadDevices()
        } catch (e) {
          console.error('解析告警消息失败:', e)
        }
      })
      stompClient.value.subscribe('/topic/anomalies', (message) => {
        try {
          const anomaly = JSON.parse(message.body)
          console.log('收到异常:', anomaly)
          loadAnomalies()
          if (selectedDevice.value === anomaly.deviceId) {
            loadDeviceAnomalies(selectedDevice.value)
          }
        } catch (e) {
          console.error('解析异常消息失败:', e)
        }
      })
    },
    onDisconnect: () => {
      console.log('WebSocket 断开连接，将自动重连...')
    },
    onStompError: (frame) => {
      console.error('WebSocket 错误:', frame.headers['message'])
    },
    onWebSocketClose: () => {
      console.log('WebSocket 连接关闭，准备重连...')
    },
    onWebSocketError: (error) => {
      console.error('WebSocket 底层连接错误:', error)
    }
  })
  stompClient.value.activate()
}

onMounted(() => {
  loadDevices()
  loadAlerts()
  loadAnomalies()
  loadRules()
  connectWebSocket()
  
  setInterval(() => {
    loadDevices()
    if (selectedDevice.value) {
      loadDeviceData(selectedDevice.value)
    }
  }, 5000)
})

onUnmounted(() => {
  if (stompClient.value) {
    stompClient.value.deactivate()
  }
})
</script>

<style scoped>
.app {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

.header {
  background: linear-gradient(135deg, #16213e 0%, #1a1a2e 100%);
  padding: 1rem 2rem;
  border-bottom: 2px solid #0f3460;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.header h1 {
  font-size: 1.5rem;
  color: #4bc0c0;
}

.header-right {
  display: flex;
  gap: 1rem;
}

.alert-banner {
  background: rgba(255, 107, 107, 0.2);
  padding: 0.5rem 1rem;
  border-radius: 4px;
  border: 1px solid #ff6b6b;
}

.alert-banner.anomaly {
  background: rgba(255, 193, 7, 0.2);
  border-color: #ffc107;
}

.blink {
  animation: blink 1s infinite;
}

@keyframes blink {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.5; }
}

.main-content {
  display: flex;
  flex: 1;
  overflow: hidden;
}

.sidebar {
  width: 400px;
  background: #16213e;
  padding: 1rem;
  overflow-y: auto;
  border-right: 1px solid #0f3460;
}

.tabs {
  display: flex;
  gap: 0.5rem;
  margin-bottom: 1rem;
}

.tab-btn {
  flex: 1;
  padding: 0.5rem 1rem;
  border: none;
  border-radius: 6px;
  background: #1a1a2e;
  color: #aaa;
  cursor: pointer;
  transition: all 0.3s;
}

.tab-btn.active {
  background: #4bc0c0;
  color: white;
}

.sidebar h2 {
  font-size: 1.1rem;
  margin-bottom: 1rem;
  color: #4bc0c0;
}

.device-list {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.device-item {
  background: #1a1a2e;
  padding: 0.75rem;
  border-radius: 8px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  cursor: pointer;
  transition: all 0.3s;
  border: 2px solid transparent;
}

.device-item:hover {
  background: #252545;
  transform: translateX(5px);
}

.device-item.selected {
  border-color: #4bc0c0;
  background: #1e3a5f;
}

.device-item.has-alert {
  border-color: #ff6b6b;
  background: rgba(255, 107, 107, 0.1);
  animation: pulse 2s infinite;
}

@keyframes pulse {
  0%, 100% { box-shadow: 0 0 0 0 rgba(255, 107, 107, 0.4); }
  50% { box-shadow: 0 0 0 10px rgba(255, 107, 107, 0); }
}

.device-id {
  font-weight: 600;
}

.temp-normal { color: #4bc0c0; }
.temp-warning { color: #ffd93d; }
.temp-critical { color: #ff6b6b; }

.content {
  flex: 1;
  padding: 2rem;
  overflow-y: auto;
}

.no-selection {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100%;
  color: #666;
  font-size: 1.2rem;
}

.device-detail h2 {
  margin-bottom: 1.5rem;
  color: #4bc0c0;
}

.chart-container {
  background: #16213e;
  border-radius: 12px;
  padding: 1.5rem;
  margin-bottom: 1.5rem;
  border: 1px solid #0f3460;
}

.chart-container h3 {
  margin-bottom: 1rem;
  color: #aaa;
  font-size: 1rem;
}

.chart-container :deep(.vue-chartjs) {
  height: 300px !important;
}

.rules-panel {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.rule-form {
  background: #1a1a2e;
  padding: 1rem;
  border-radius: 8px;
}

.rule-form h3,
.rule-form h4 {
  color: #4bc0c0;
  margin-bottom: 0.75rem;
  font-size: 1rem;
}

.form-input,
.form-textarea,
.form-select {
  width: 100%;
  padding: 0.5rem;
  margin-bottom: 0.5rem;
  background: #16213e;
  border: 1px solid #0f3460;
  border-radius: 4px;
  color: #eee;
}

.form-input.small {
  width: auto;
}

.form-select.small {
  flex: 1;
  min-width: 80px;
}

.form-row {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin-bottom: 0.5rem;
}

.form-row label {
  color: #aaa;
  font-size: 0.9rem;
  min-width: 80px;
}

.conditions-section {
  margin: 1rem 0;
  padding-top: 1rem;
  border-top: 1px solid #0f3460;
}

.condition-item {
  background: #16213e;
  padding: 0.5rem;
  border-radius: 4px;
  margin-bottom: 0.5rem;
}

.condition-row {
  display: flex;
  gap: 0.25rem;
  align-items: center;
}

.form-actions {
  display: flex;
  gap: 0.5rem;
  margin-top: 1rem;
}

.btn {
  padding: 0.5rem 1rem;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-weight: 500;
}

.btn-primary {
  background: #4bc0c0;
  color: white;
}

.btn-secondary {
  background: #666;
  color: white;
}

.btn-small {
  padding: 0.25rem 0.5rem;
  font-size: 0.8rem;
  background: #4bc0c0;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

.btn-small.danger {
  background: #ff6b6b;
}

.btn-small.active {
  background: #666;
}

.rules-list {
  background: #1a1a2e;
  padding: 1rem;
  border-radius: 8px;
}

.rules-list h4 {
  color: #4bc0c0;
  margin-bottom: 0.75rem;
  font-size: 1rem;
}

.rule-item {
  background: #16213e;
  padding: 0.75rem;
  border-radius: 6px;
  margin-bottom: 0.5rem;
  border-left: 3px solid #4bc0c0;
}

.rule-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 0.25rem;
}

.rule-name {
  font-weight: 600;
  color: #eee;
}

.rule-severity {
  font-size: 0.75rem;
  padding: 0.125rem 0.5rem;
  border-radius: 4px;
  text-transform: uppercase;
}

.rule-severity.critical { background: #ff6b6b; color: white; }
.rule-severity.high { background: #ff9800; color: white; }
.rule-severity.medium { background: #ffc107; color: black; }
.rule-severity.low { background: #4caf50; color: white; }

.rule-desc {
  color: #aaa;
  font-size: 0.85rem;
  margin-bottom: 0.5rem;
}

.rule-actions {
  display: flex;
  gap: 0.5rem;
}

.anomalies-section {
  background: #16213e;
  border-radius: 12px;
  padding: 1.5rem;
  border: 1px solid #0f3460;
}

.anomalies-section h3 {
  color: #ffc107;
  margin-bottom: 1rem;
}

.anomaly-item {
  background: rgba(255, 193, 7, 0.1);
  border: 1px solid #ffc107;
  border-radius: 8px;
  padding: 1rem;
  margin-bottom: 0.75rem;
}

.anomaly-header {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  margin-bottom: 0.5rem;
}

.anomaly-rule {
  font-weight: 600;
  color: #ffc107;
}

.anomaly-severity {
  font-size: 0.75rem;
  padding: 0.125rem 0.5rem;
  border-radius: 4px;
  text-transform: uppercase;
}

.anomaly-severity.critical { background: #ff6b6b; color: white; }
.anomaly-severity.high { background: #ff9800; color: white; }
.anomaly-severity.medium { background: #ffc107; color: black; }
.anomaly-severity.low { background: #4caf50; color: white; }

.anomaly-time {
  color: #888;
  font-size: 0.85rem;
  margin-left: auto;
}

.anomaly-msg {
  color: #ddd;
  margin: 0;
}
</style>
